[tool.black] # Black Formatter for .py files
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | (.*interactive_runner.py)
  | _build
  | buck-out
  | build
  | dist
)/
'''
