[tool.black] # Black Formatter for .py files
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | testlib
  | _build
  | buck-out
  | build
  | dist
)/
'''
