name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ubuntu-22.04, windows-latest]
                gcc: [9, 11]
                python-version: ['3.11', '3.12', '3.13']
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
                submodules: 'recursive'

          - name: Set up GCC (MacOS, Linux)
            if: runner.os != 'Windows'
            uses: egor-tensin/setup-gcc@v1.3
            with:
                version: ${{ matrix.gcc }}

          - name: Set up MinGW (Windows)
            if: runner.os == 'Windows'
            uses: msys2/setup-msys2@v2
            with:
                msystem: MINGW64
                update: true
                install: 'mingw-w64-x86_64-gcc'

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix['python-version'] }}

          - name: Update submodules
            run: git submodule update --init

          - name: Install python-tabulate
            run: python -m pip install tabulate

          - name: Copy config files
            shell: bash
            run: cp example/config/* src

          - name: Copy sample C++ solutions
            shell: bash
            run: cp -r example/workspace src

          - name: Run stress.py
            run: python src/stress.py

          - name: Run create_problem.py
            run: python src/create_problem.py